const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, LevelFormat,
        Table, TableRow, TableCell, WidthType, ShadingType, TableLayoutType } = require('docx');
const fs = require('fs');

const { stagePath } = require('./stage');
const P = (text, opts = {}) => new Paragraph({ spacing: { after: 200 }, ...opts, children: [new TextRun({ text, ...(opts.run || {}) })] });
const PS = (segs, opts = {}) => new Paragraph({ spacing: { after: 200 }, ...opts, children: segs.map(s => new TextRun({ text: s.t, bold: !!s.b, italics: !!s.i, color: s.c })) });
const DM = (t) => ({ t, b: true, c: "5B1F1F" });   // DM-only marker: bold book-red
const H1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, keepNext: true, children: [new TextRun(t)] });
const H2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, keepNext: true, children: [new TextRun(t)] });
const H3 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_3, keepNext: true, children: [new TextRun(t)] });
const BULLET = (segs) => new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 120 }, children: segs.map(s => new TextRun({ text: s.t, bold: !!s.b, italics: !!s.i, color: s.c })) });
const B = (lead, rest) => PS([{ t: lead + " ", b: true }, { t: rest }]);
const BUL = (lead, rest) => BULLET(lead ? [{ t: lead + " ", b: true }, { t: rest }] : [{ t: rest }]);
const { Table: LTable, TableRow: LRow, TableCell: LCell, WidthType: LW, ShadingType: LS, TableLayoutType: LL } = require('docx');
// Column widths in twips. docx-js emits a dummy equal-width <w:tblGrid> when
// columnWidths is absent, and LibreOffice honours that grid over the per-cell
// percentages -- every table renders with evenly split columns. Passing the
// grid explicitly, with a fixed layout, is what makes the widths array mean
// anything. Proportions are what matter; tblW=100% governs the total.
const CW = (w) => { const t = w.reduce((a, b) => a + b, 0); return w.map((x) => Math.round(9026 * x / t)); };

const lcell = (text, opts = {}) => new LCell({ width: { size: opts.w || 20, type: LW.PERCENTAGE }, shading: opts.head ? { type: LS.CLEAR, fill: "E4DCCB" } : undefined, margins: { top: 50, bottom: 50, left: 90, right: 90 }, children: [new Paragraph({ spacing: { after: 0 }, alignment: AlignmentType.LEFT, indent: { firstLine: 0 }, children: [new TextRun({ text, bold: !!opts.head, size: 18 })] })] });
const ltable = (headers, widths, rows) => new LTable({ width: { size: 100, type: LW.PERCENTAGE }, columnWidths: CW(widths), layout: LL.FIXED, rows: [ new LRow({ cantSplit: true, tableHeader: true, children: headers.map((h, i) => lcell(h, { head: true, w: widths[i] })) }), ...rows.map(r => new LRow({ cantSplit: true, children: r.map((v, i) => lcell(v, { w: widths[i] })) })) ] });

const BOX = (text) => new Paragraph({ spacing: { after: 200 }, shading: { type: ShadingType.CLEAR, fill: "EFEAE0" }, indent: { left: 360, right: 360 }, children: [new TextRun({ text, italics: true })] });
const mod = (v) => { const m = Math.floor((v - 10) / 2); return (m >= 0 ? "+" : "\u2212") + Math.abs(m); };
const abCell = (text, bold) => new TableCell({ width: { size: 16.6, type: WidthType.PERCENTAGE }, shading: bold ? { type: ShadingType.CLEAR, fill: "E4DCCB" } : undefined, children: [new Paragraph({ keepNext: !!bold, alignment: AlignmentType.CENTER, spacing: { after: 40, before: 40 }, children: [new TextRun({ text, bold: !!bold, size: 20 })] })] });
const SB = (d) => {
  const out = [];
  out.push(new Paragraph({ spacing: { before: 240, after: 40 }, children: [new TextRun({ text: d.name, bold: true, size: 26, color: "5B1F1F" })] }));
  out.push(PS([{ t: d.meta, i: true }], { spacing: { after: 120 } }));
  out.push(B("Armor Class:", d.ac)); out.push(B("Hit Points:", d.hp)); out.push(B("Speed:", d.speed));
  out.push(new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, columnWidths: CW([1, 1, 1, 1, 1, 1]), layout: TableLayoutType.FIXED, rows: [
    new TableRow({ cantSplit: true, children: ["STR", "DEX", "CON", "INT", "WIS", "CHA"].map(h => abCell(h, true)) }),
    new TableRow({ cantSplit: true, children: [d.str, d.dex, d.con, d.int, d.wis, d.cha].map(v => abCell(v + " (" + mod(v) + ")")) })
  ] }));
  out.push(P("", { spacing: { after: 60 } }));
  if (d.skills) out.push(B("Skills:", d.skills));
  if (d.saves) out.push(B("Saving Throws:", d.saves));
  if (d.resist) out.push(B("Damage Resistances:", d.resist));
  if (d.immune) out.push(B("Damage Immunities:", d.immune));
  if (d.condimmune) out.push(B("Condition Immunities:", d.condimmune));
  if (d.vuln) out.push(B("Damage Vulnerabilities:", d.vuln));
  if (d.senses) out.push(B("Senses:", d.senses));
  if (d.langs) out.push(B("Languages:", d.langs));
  out.push(B("Challenge:", d.cr));
  (d.traits || []).forEach(t => out.push(PS([{ t: t.n + ". ", b: true, i: true }, { t: t.t }])));
  if (d.actions && d.actions.length) { out.push(PS([{ t: "ACTIONS", b: true }], { spacing: { before: 80, after: 80 } })); d.actions.forEach(a => out.push(PS([{ t: a.n + ". ", b: true, i: true }, { t: a.t }]))); }
  if (d.reactions && d.reactions.length) { out.push(PS([{ t: "REACTIONS", b: true }], { spacing: { before: 80, after: 80 } })); d.reactions.forEach(a => out.push(PS([{ t: a.n + ". ", b: true, i: true }, { t: a.t }]))); }
  return out;
};
const docShell = (children) => new Document({
  numbering: { config: [{ reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 280, hanging: 280 } } } }] }] },
  styles: {
    default: { document: { run: { font: "Georgia", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Georgia", color: "3B2F2F" }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 27, bold: true, font: "Georgia", color: "3B2F2F" }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 24, bold: true, italics: true, font: "Georgia", color: "3B2F2F" }, paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 2 } }
    ]
  },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } }, children }]
});
const title = (children, main, sub) => {
  children.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: main, bold: true, size: 40 })] }));
  children.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "The Qilvayas Symphony", italics: true, size: 24 })] }));
  children.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 360 }, children: [new TextRun({ text: sub, italics: true, size: 22, color: "5B1F1F" })] }));
};

// ============================================================
// SESSION 5 \u2014 DEAD LETTERS
// ============================================================
const c5 = [];
title(c5, "Session Five: Dead Letters", "An adventure for 4\u20136 characters of 5th level \u2014 the company\u2019s first contract, the document underworld, and the spymaster at the end of the thread");

c5.push(H1("Overview"));
c5.push(P("The party are graduates now: chartered, marked in sealed records as Proven, and open for business. Session Five is their first real contract \u2014 a deniable commission from the Lord Chamberlain\u2019s office to trace who has been buying the seals of dead imperial institutions \u2014 and it walks them through Rivergate\u2019s document underworld, into a chess match with the Office of Omens, through a dockside misunderstanding with professional consequences, and finally to a back office where the thread they have been pulling turns out to end in the hand of Mistress Averil Shen, the throne\u2019s own spymaster \u2014 who has been walking the same trail from the other end, because the trail was first walked by Empress Nyreeza."));
c5.push(P("Designed for a five-hour core. Pacing budget: the shingle and the clerk (40 minutes); Rivergate \u2014 the district open to be walked, the seal-dealer among its nine locations (70 minutes); the dead letters, worked as a cipher rather than a translation (40 minutes); the Office\u2019s attention (55 minutes); the Inkhands\u2019 door (40 minutes); the Shen reveal (60 minutes); closing choices (15 minutes). Optional content adds up to two further hours \u2014 see Optional Content. This is deliberately a light-combat session: one avoidable brawl and one avoidable ambush. The city is the dungeon; the corridors are made of people."));
c5.push(B("On the forty minutes for the letters.", "They are new to the budget and they are taken from the two big scenes, not added on top. The letters were previously read; now they are solved, and a cipher that resolves in five minutes is not a cipher. If the table is stuck at thirty minutes, Mosse sells them the concordance \u2014 that is what he is for, and buying the answer is one of the four intended solutions rather than a rescue."));

c5.push(H2("What Is Actually Happening (DM Only)"));
c5.push(P("Three years ago, Empress Nyreeza needed to research the empire\u2019s oldest records without leaving a trail through official requisitions. Her method was elegant: she quietly purchased the seals of abolished imperial offices \u2014 dead institutions whose stamps still open archive doors, because no clerk in the empire is paid enough to question a seal that looks right \u2014 and used forged dead authority to work off the books. Mistress Averil Shen, reconstructing the Empress\u2019s last year step by step, discovered the method and has spent months buying up the same categories of dead seals: partly to retrace Nyreeza\u2019s access, partly to take the tool off the market before anyone else notices it exists."));
c5.push(P("Lord Chamberlain Kessin noticed anyway \u2014 not the why, only the pattern: someone with money and discipline is quietly cornering the market in defunct authority over Founder\u2019s Wall district records. Kessin suspects his rival Shen but cannot investigate her openly without tipping his hand, so he does what chamberlains do: he hires deniable outsiders. The party\u2019s commission is real, the pay is real, and the entire job is one court officer aiming a newly chartered mercenary company at another court officer without telling either of them. Meanwhile, the Office of Omens has the party under active surveillance \u2014 the copyist on Vaelindra\u2019s ground floor reports to the Office, and has for years (Vaelindra knows, and feeds the arrangement carefully curated chaff) \u2014 and Prelate Odell is building a jurisdictional case that the party\u2019s vision was Vaelindra\u2019s suggestion, which would make her legally examinable. Every faction in this session is honest by its own lights. That is what makes it dangerous."));

c5.push(H1("Scene 1: The Shingle and the Clerk"));
c5.push(BOX("The company office is one flight above Master Verro\u2019s map shop on Coppergate\u2019s Fourth Lane: two rooms, one window that opens and one that lies about it, a strategic view of a laundry line, and \u2014 as of this morning \u2014 a sign. The sign took four days and two arguments. It hangs slightly crooked, which the landlady, the Widow Brakka, has already pointed out twice, along with the rent date, the house rules concerning \u201Csorcery, livestock, and musicians,\u201D and the fact that she has taken the liberty of feeding you, because you are all far too thin to overthrow anything."));
c5.push(P("Open with texture and let the table enjoy it: the office, the sign (revisit the company name and charter from Session Zero \u2014 hang the charter on the wall, and beside it the Concord\u2019s register receipt, which is the half that actually matters and which the party queued for in Session Four), Brakka\u2019s tyrannical generosity, the first trickle of walk-in work offers (a lost cat with a suspiciously large reward; a merchant who wants his rival \u201Clightly investigated\u201D; decline or note for later). Fifteen to twenty minutes of the party simply being what they planned to become \u2014 the campaign owes them this beat before it complicates their lives again."));
c5.push(P("Then the clerk. Ossian Pell of the Chamberlain\u2019s office is young, gray-clothed, gray-mannered, and precisely as forgettable as his office trains its people to be. His offer, delivered from memory with the door closed: a commission, 150 gp on completion, strictly unattributed. Someone has been purchasing the seals and stamps of abolished imperial offices \u2014 specifically, in recent months, three offices whose defunct authority touches the census and property rolls of the Founder\u2019s Wall district, the oldest records in Aenodira. The chamberlery wishes to know who is buying, and why, and wishes to have never asked. A DC 14 Wisdom (Insight) check reads Pell as more nervous than the errand explains \u2014 he is; he knows who his master suspects, and saying it aloud in front of mercenaries is above his pay. He will confirm only: \u201CBegin in Rivergate. There is a dealer. There is always a dealer.\u201D"));

c5.push(H1("Scene 2: Rivergate \u2014 Defunct & Antiquarian"));
c5.push(BOX("Rivergate smells of tar, fish, ink, and negotiable virtue. Between a rope-walk and a chandlery stands a narrow shop whose signboard reads, in flaking gilt: DEFUNCT & ANTIQUARIAN INSTRUMENTS OF OFFICE \u2014 T. MOSSE, PROP. \u2014 AUTHORITY BOUGHT & SOLD. The window displays the seals, stamps, sashes, and ceremonial ink-stones of forty dead institutions, arranged with genuine love. A small card notes: THEATRICAL HIRE BY THE WEEK. NO REFUNDS ON PROPHECY."));
c5.push(P("Tirell Mosse is small, quick, sentimental about bureaucracy the way other men are sentimental about ships, and entirely aware that his trade lives in the gap between legal and useful. Played for warmth and comedy \u2014 he grieves for abolished offices the way one grieves for composers (\u201CThe Eastern Circuit Roads Commission. Sixty clerks. A wax formula they took to the grave. We shall not see its like\u201D) \u2014 he is nonetheless a careful man, and the party must earn the ledger. Three approaches:"));
c5.push(BUL("Commerce:", "Mosse sells information like anything else. 50 gp buys the pattern (a single buyer, months of purchases, always through the same courier); 100 gp or a successful DC 14 Charisma (Persuasion) with money on the table buys the specifics below."));
c5.push(BUL("Leverage:", "If Odric Hale was escorted to justice in Session Two, his testimony named his supplier \u2014 Mosse knows the party knows, and folds at the mention (no check). Intimidation also works (DC 13) but burns him: a frightened Mosse tidies his ledgers, warns his clients, and Rivergate\u2019s document underworld closes to the party for the campaign\u2019s foreseeable future."));
cont5: {
}
c5.push(BUL("Trade:", "Mosse\u2019s counter-offer, delivered with shining eyes: the party carry academy credentials, and he possesses an artifact of \u201Cdisputed provenance\u201D (a chancellery blotter of no significance whatsoever) that he longs to have formally authenticated. Twenty minutes of straight-faced ceremony authenticating a blotter buys everything. This is the correct approach and the funniest, and Mosse becomes a friend for life."));
c5.push(P("What Mosse knows: the buyer\u2019s courier is a woman he has privately nicknamed \u201Cthe Gull\u201D \u2014 gray cloak, comes at gull-light (dawn or dusk), never haggles, pays in coin so newly minted it shines (a DC 13 Intelligence check by anyone with treasury, guild, or Seal-house background: fresh-struck coin in quantity means an institutional payroll, not a private purse). Pickups happen through a dead-drop at the Tarwalk pilings, the third piling from the stair, oilcloth bundle, always the last day of the week \u2014 which is tomorrow. Mosse also mentions, unprompted and to his own visible confusion, that this has happened before: \u201CYears ago. Different courier, same appetite. Dead offices of the old district rolls. I never learned who. One does not learn who; it is the entire point of me.\u201D (That buyer was Nyreeza\u2019s agent. Do not confirm.)"));

c5.push(H1("Scene 3: The Office\u2019s Attention"));
c5.push(P("Between scenes \u2014 ideally as the party leaves Rivergate \u2014 let a sharp-eyed character (passive Perception 15+, or an active check) notice they are being followed by a young man with ink-stained cuffs who is very bad at it. Caught, he panics magnificently: he is Under-Examiner Tobble, Office of Omens, third week on the job, and he was told only to \u201Cobserve the claimants and note who they meet.\u201D He is so relieved not to be stabbed that he becomes a fountain of accidental disclosure: the Office has a file; the file has a number; the number has a prelate. That afternoon, the formal summons arrives at the office \u2014 thick paper, beautiful hand, the Office\u2019s seal: Prelate Sarvin Odell requests the party\u2019s voluntary attendance at the Sanctum at their earliest convenience, where \u201Cearliest\u201D is underlined in a way that has clearly been practiced."));
c5.push(BOX("Prelate Sarvin Odell receives you in a room designed to make visitors feel filed: shelves of identical gray boxes to the ceiling, a desk with nothing on it but one folder, and a window placed to light your faces and not his. He is sixty, soft-spoken, and unfailingly kind in the way of a man who has never once needed to raise his voice to ruin anyone. \u201CSit, please. Tea? No? Wise \u2014 it\u2019s terrible. Now.\u201D He opens the folder. \u201CLet us talk about your dream.\u201D"));
c5.push(P("Run the interview as verbal chess, sixty minutes of it, and let it be genuinely tense \u2014 Odell is not a fool and this is his arena. His two goals, never stated: first, to get any party member to agree, in any phrasing, that the vision\u2019s significance was suggested to them by Vaelindra (each such statement is an evidentiary brick in the jurisdictional wall he is building around her \u2014 a claimant influenced by an unsanctioned interpreter is Church business); second, failing that, to have the party voluntarily register as claimants of divine contact, which places them \u2014 and everyone who counsels them \u2014 under the Office\u2019s examination authority. He probes with soft, precise questions: When did you first believe the dream mattered? Who told you it was shared? Who benefits from your belief? A Seal-house character recognizes the trap structure outright (no check); others may make DC 15 Wisdom (Insight) to feel the questions herding them. Safe answers exist \u2014 the vision was self-evidently shared before any consultation; no interpretation was sought, only historical context; the party claims nothing and therefore registers nothing \u2014 and Odell receives good answers with unfeigned professional pleasure, like a fencer saluting. Divergence outcomes at the end of this document. However it ends, his last line is the same:"));
c5.push(BOX("\u201CThank you. You have been more helpful than you know \u2014 they always are, but you especially.\u201D He closes the folder. \u201COne kindness, freely given, because you are young and the woman is clever: whatever she is to you \u2014 historian, grandmother, oracle \u2014 the Matron\u2019s law does not recognize the category. Categories are my work. I am very good at my work.\u201D"));

c5.push(H1("Scene 4: The Inkhands"));
c5.push(P("The Tarwalk dead-drop must be watched to catch the Gull \u2014 which means a night among the pilings, and the pilings have owners. The Inkhands run protection on Rivergate\u2019s document trade (their name is their contract: cross them and they blot you from the ledgers), and a crew of strangers lurking near Mosse\u2019s dead-drop reads to them as exactly one thing: rival operators moving on their territory. Brune Halloc \u2014 broad, amiable, and carrying a boat-hook like punctuation \u2014 arrives with four Inkhand Enforcers (five for a party of five, six for six) to explain the misunderstanding the party is about to have."));
c5.push(P("This is a negotiation wearing a brawl\u2019s clothes. Halloc genuinely prefers not to fight people with visible sword-calluses and academy posture; a DC 13 Charisma (Persuasion or Intimidation) \u2014 with advantage if the party invokes Mosse as a reference or offers the Inkhands\u2019 standard \u201Cvisitor\u2019s consideration\u201D (10 gp) \u2014 converts the confrontation into an arrangement, and Halloc\u2019s crew will even keep casual watch over the stakeout for professional courtesy. Scaling, if it comes to blows: baseline (4 characters) is Halloc plus 3 Inkhand Enforcers. For 5 characters, add 1 enforcer. For 6, add 2, and Halloc holds the gangplank so the party must come to him one or two at a time \u2014 which is how a dock boss who does not want a killing keeps it from becoming one. The Inkhands fight nonlethally with fists, hooks, and saps, quit at half strength, and hold no grudge afterward that a round of drinks cannot settle \u2014 but a party that draws steel and kills on the docks discovers that Rivergate remembers, the Garrison asks questions, and every ledger in the district develops sudden illiteracy regarding their inquiries."));

c5.push(H1("Scene 5: The Gull, and the Hand at the End of the Thread"));
c5.push(P("At gull-light, she comes \u2014 gray cloak, unhurried, professionally forgettable. The party can shadow her (opposed Stealth; she is good, DC 16, and the route is designed to shed followers through a fish market and a temple crowd), intercept her (she does not resist, does not speak, and produces a writ of \u2014 of all things \u2014 the Bureau of Correspondence), or mark her and trace the route later. All roads lead to the same unmarked door behind the Bureau\u2019s public post-office frontage in the Exchange district, and through it \u2014 by invitation, because the moment the party commits to the door, it opens from within \u2014 to a small warm room with excellent tea and Mistress Averil Shen pouring it."));
c5.push(BOX("\u201CSit. The tea is good \u2014 unlike the Prelate\u2019s, which I\u2019m told you had the sense to refuse.\u201D She is fifty, small, and stillness-made-flesh; the Gull stands at her shoulder like a folded letter. \u201CYou stalk like scholars, which is to say: loudly, but with excellent notes. So. The Chamberlain has hired children to find out what I am buying, and the children have actually found me, which is more than his last three attempts managed. Before we discuss what you will tell him \u2014 and we will \u2014 I am going to show you why the question matters, because someone in this city ought to know besides me.\u201D She sets a single sheet on the table. \u201CI have spent two years buying dead seals to learn how a living Empress vanished. She bought them first. She was cleverer than all of us. And on the last day anyone saw her, she filed one final document under a dead office\u2019s authority \u2014 and I cannot read it.\u201D The sheet is covered in a careful, hurried cipher. Whoever carries the Cold Door rubbing feels their pulse jump: it is the same hand."));
c5.push(P("Shen\u2019s proposition: pool what they hold \u2014 her requisition trail and the ciphered document against the party\u2019s rubbing and their academy access to Vell \u2014 and pursue the Empress\u2019s trail together, quietly, off every book in the empire. Her terms are blunt: Kessin gets a cover story (she will even draft it \u2014 \u201Cthe buyer was a Velmarene collector; the trail is cold\u201D), Odell gets nothing, and the throne gets nothing until there is something worth a throne\u2019s attention, because \u2014 and here she is honest in a way that costs her \u2014 \u201Cthe Empress hid this from her own son. I have wondered for three years whether she was protecting the investigation from the court, or protecting him from the answer. Until I know which, neither will I.\u201D What the party does with all of this \u2014 the alliance, the cover story, the truth owed or not owed to Pell and Kessin \u2014 is the session\u2019s closing choice, and every option forks (see Diverging Paths). Pay them their 150 gp regardless: whatever they report, the commission was technically completed. Session ends on the walk home from the Bureau, the city lamplit, one of them carrying two documents in the same dead woman\u2019s hand."));


// ============ RIVERGATE, KEYED ============
c5.push(H1("Rivergate, Keyed"));
c5.push(P("Session Five is an investigation, and an investigation needs a place with corners. Rivergate is the capital\u2019s lowest district \u2014 below the waterline in every sense, built into the old river terraces so that its streets descend and its cellars are older than its houses. Nine locations, all within twenty minutes' walk of each other, all usable in any order."));
c5.push(B("Running it as a district, not a corridor.", "The party has a thread and a name. Let them choose where to pull. Every location below yields something to a party who arrives with the right question and something else to a party who arrives with the wrong one, and none of them is a gate that must be opened before the next. If they never visit V4 at all, the session still works."));
c5.push(B("V1. The Shingle.", "The river stair and the mud below it, where the district gets its name and where things wash up. The clerk\u2019s scene opens here. At low water the shingle is forty feet of black silt and broken crockery; at high water it is not there."));
c5.push(B("V2. Defunct & Antiquarian.", "Tirell Mosse\u2019s shop: a seal-dealer\u2019s premises, narrow, four storeys of stock in two rooms, smelling of shellac. Mosse buys and sells dead men\u2019s seals, entirely legally, and knows precisely where the line is because he has spent thirty years standing on it."));
c5.push(B("V3. The Letter-House.", "A public scriptorium where the unlettered pay to have letters written and read. Four desks, a queue, and the single richest source of local information in the district, because everyone in Rivergate who cannot write has told a stranger their business here."));
c5.push(B("V4. The Inkhands' Door.", "Not a shop. A door in an alley off the fish market, with a chop nailed to it that means something. See the trap block; the door itself is the district\u2019s first real test of whether the party can be trusted."));
c5.push(B("V5. The Fish Market.", "Loud, wet, and the district\u2019s only genuinely public space. Everyone passes through here. A party who wants to be seen comes here; a party who wants to see comes here and stands still."));
c5.push(B("V6. Brune Halloc\u2019s Yard.", "The dock boss\u2019s ground: a timber yard that is not primarily about timber. Halloc holds the district\u2019s labor and therefore its silence, and he is entirely open about the arrangement."));
c5.push(B("V7. The Waterline Cellars.", "Beneath everything: a connected system of flooded and half-flooded undercrofts running under four streets. Where the wererat rumor lives. The Watch denies them; the Inkhands charge a surcharge for jobs below the waterline; both facts are true and neither is an explanation."));
c5.push(B("V8. The Gull.", "A tavern on the stair with a view of the shingle, where Session Five\u2019s last scene lands. Two rooms, one window, and a landlord who has never once been surprised."));
c5.push(B("V9. The Watch Post.", "Two constables and a book. They are not corrupt; they are outnumbered, and they have made a series of reasonable decisions over twenty years that add up to not going below the waterline. A party that treats them as enemies loses the most useful ally in the district."));

c5.push(H1("The Dead Letters (Puzzle)"));
c5.push(P("The letters are the session\u2019s object and they should be an object at the table: paper, in hand, unreadable, and slowly yielding. This is the campaign\u2019s first cipher and it is deliberately solvable in four different ways, none of them faster than the others."));
c5.push(BOX("Six letters, water-stained, in a bundle tied with tarred string. The hand is small, fast, and educated. The words are Old Imperial and they are also not: every third word is a word, and the rest is a wall of legal shorthand, register abbreviations, and shelf-marks. There is no salutation and no signature. On the outside of the bundle, in the same hand, one line that is plainly a note to the writer\u2019s own self rather than to anyone else: FOURTH BOOK, NOT THE THIRD."));
c5.push(P("The letters are written in a register cipher: the meaningful text is carried by the shelf-marks, and the surrounding shorthand is padding. FOURTH BOOK, NOT THE THIRD tells the reader which Book of the Laws supplies the numbering \u2014 Book Four, of Seals and Record, not Book Three. A reader who tries Book Three gets plausible nonsense, which is the trap and which should be allowed to run for a while."));
c5.push(B("Solution one \u2014 the Seal education.", "A House of the Seal character who has held the bundle for an hour can identify the register-cipher form (it is a real archival practice, not a code invented for concealment) at DC 13 Intelligence (Investigation). They still need Book Four, and the note on the outside is the only thing that supplies it."));
c5.push(B("Solution two \u2014 Mosse.", "Tirell Mosse (V2) has seen this before, will say so, will not read it for them, and will point them at what does: he sells the register concordance, secondhand, for eleven Zhuven, and he will not haggle because he thinks they are getting a bargain and he is right."));
c5.push(B("Solution three \u2014 the Letter-House.", "The scriveners at V3 read and write for a living and one of them is far better educated than the work requires. She will do it for money, and she will read the letters while she does, and that is the cost \u2014 it is not a betrayal, it is just that she now knows."));
c5.push(B("Solution four \u2014 brute force.", "Twelve hours, two characters, a copy of the Laws, and any Intelligence-based check the DM likes at DC 15 with advantage for anyone with a legal or clerical background. It works. It costs a day, and in this session a day is expensive, and a party who spends it should not be punished for it in any other way."));
c5.push(PS([DM("DM Only: "), { t: "the letters are not a message to anyone. They are working notes \u2014 somebody\u2019s private research, written in a cipher of professional convenience rather than secrecy, by a person who never expected to be read and who was therefore completely honest. That is why they are dangerous. The hand is the same hand as the SEE ALSO card from the Undervault registry, and a party who kept that card and lays it beside these has made the connection two sessions early, which is allowed and which should be met with silence." }]));

c5.push(H1("Traps"));
c5.push(B("The Inkhands' Door (V4).", "Not a mechanical trap. A social one with mechanics, which is the district\u2019s whole character."));
c5.push(BUL("The chop:", "the mark nailed to the door names the current arrangement. DC 13 Intelligence (Investigation), or automatic for an Inkhand background: it means open to trade, no Watch, no names. A party that knocks having read it is speaking the language."));
c5.push(BUL("Knocking wrong:", "any approach that names the Watch, produces a warrant, or mentions the academy gets a polite refusal and a door that does not open again for that party, ever. There is no check to reverse this. It is not a puzzle to be failed and retried; it is a first impression."));
c5.push(BUL("Knocking right:", "a coin, a chop of their own, or a name that carries \u2014 Halloc\u2019s, Mosse\u2019s, or anyone the party has already dealt with squarely \u2014 opens it. DC 12 Charisma (Deception or Persuasion) if they have none of those and are simply plausible."));
c5.push(BUL("What is behind it:", "unlicensed scrollwork at trade prices, and people who are very good or very quick. Both, in one case."));
c5.push(B("The Waterline Stair (V7).", "Environmental hazard. The cellars flood on the tide, twice a day, without warning to anyone who does not know the tide."));
c5.push(BUL("Effect:", "water rises 3 feet over ten minutes and holds for two hours. In the lowest undercrofts that is chest-deep and the current in the connecting arches is strong: DC 12 Strength (Athletics) to move against it, and a failed check means swept one chamber along."));
c5.push(BUL("Warning:", "DC 12 Wisdom (Survival) or Intelligence (Nature) reads the tide-line on the wall before descending. Anyone from Rivergate, Velmareth, or the Skellvard knows without a roll and will mention it if asked."));
c5.push(BUL("The point:", "the cellars are a time limit rather than a monster. A party that goes down without checking the tide has two hours to work and does not know it."));
c5.push(B("The Surcharge.", "Below the waterline the Inkhands charge double, and they have never explained why, and they will not. A party who asks gets a shrug. A party who asks a third time gets told to ask the Watch, which is a joke, and the constables at V9 will not laugh."));

c5.push(H1("Encounters in Rivergate"));
c5.push(P("Roll a d8 whenever the party crosses the district, or when an investigation stalls and needs a shove."));
c5.push(ltable(["d8", "What Happens"], [11, 89], [
  ["1", "A scrivener from the Letter-House, off shift, who will trade a drink for the district\u2019s gossip and mean it."],
  ["2", "Two of Halloc\u2019s men, not hostile, walking the same way the party is walking, for four streets."],
  ["3", "An Office of Omens examiner asking after somebody, politely, door to door, with a list."],
  ["4", "Giant rats (2d4) out of a cellar grate at dusk, and the way the street reacts \u2014 nobody screams, everybody moves."],
  ["5", "A body on the shingle at low water, three days in the river, and the question of whose Vigil this is."],
  ["6", "A Watch constable from V9 who recognizes the party and would rather they told him what they are doing than not."],
  ["7", "An unlicensed healer working out of a doorway, competent, terrified, and one denunciation from a Book Three prosecution."],
  ["8", "The tide, coming in, and a street that was passable an hour ago."]
]));

c5.push(H1("Handouts \u2014 Session Five"));
c5.push(H2("Handout A \u2014 One of the Dead Letters"));
c5.push(BOX("...reg. IV.11.9 sub. iv \u2014 and the same again at IV.11.14, which cannot be an error twice. Sub-clause reads DEPOSITED, NOT RECEIVED. cf. IV.9.2, IV.9.7, IV.9.31 (all three, all the same season). Whoever kept this Book was not confused. Whoever kept this Book was being careful. Query the Leaf on all six. Query who had the Leaf. IV.11.9 again \u2014 the Hand is not the Hand it should be."));
c5.push(P("Hand this over as soon as the party opens the bundle, before they can read it, and let them stare at it. It is deliberately eighty percent noise. The three readable sentences are the whole session."));
c5.push(H2("Handout B \u2014 The Bundle\u2019s Outer Wrap"));
c5.push(BOX("FOURTH BOOK, NOT THE THIRD"));
c5.push(P("Written on the outside, in the same hand, to nobody. This is the key and it is free, and the players will spend an hour deciding it must mean something more complicated."));
c5.push(H1("Optional Content (Beyond the Five-Hour Core)"));
c5.push(B("The Bartleby Provision (~45 minutes):", "A formal letter from Professor Dail: with the Undervault\u2019s eastern wing under masonry, its resident \u201Ccustodial asset\u201D requires temporary care, and the party are the only living graduates it likes. Bartleby is delivered to the company office in a crate labeled ABSOLUTELY FURNITURE. What follows is a landlady crisis (Brakka\u2019s house rules did not anticipate this and she negotiates with the mimic directly, and wins), a client meeting conducted while a cabinet breathes in the corner, and \u2014 the buried payload \u2014 a moment late at night where Bartleby, who has lived above the Undercourt for four centuries, refuses to imitate anything and simply watches the floor, and the medallion in the desk drawer goes cold. Comedy that ends on a single quiet chill: even the joke NPC knows something is down there."));
c5.push(B("A Night at the Patched Standard (~30 minutes):", "The company\u2019s local: a scholars\u2019 and soldiers\u2019 tavern off Scholar\u2019s Row whose sign is a legion banner darned so many times that regulars claim it is now entirely made of repairs, \u201Clike the empire.\u201D Use it to celebrate the charter: Fenn appears and holds court on the party\u2019s Proving performance; Professor Vorn (if met in Session Two) is mid-lecture at the corner table, to pigeons of the human variety; a toast to absent friends lands on Dren\u2019s medallion and goes quiet in the good way. Pure texture and bond-maintenance \u2014 the scenes players remember when the campaign later gets dark."));
c5.push(B("The Farrowgate Client (~45 minutes):", "A knock after hours: a Farrowgate mother \u2014 one of Semya\u2019s people if they were not resettled, a stranger if they were \u2014 whose daughter took good wages at a castle in the Suthmark hills and stopped writing four months ago. She coughs twice while she talks \u2014 into her sleeve, with the practiced economy of someone who has been doing it for years \u2014 and apologizes for it, which is somehow worse. It is the Damp, Farrowgate\u2019s own complaint, bred by the district\u2019s crowding and its standing water; it is mundane, it has nothing to do with anything under the city, and the DM should resist every instinct to make it mean more than it does. A cleric in the party can end the active case in six seconds and will not have touched the cause. She cannot pay. She has brought, because it is everything she has, a jar of preserved plums and the daughter\u2019s letters \u2014 the last of which mentions \u201Cthe Countess\u2019s kindness\u201D and the odd rule that the maids must never draw well-water after dark. Taking the case (there is no fee; there is only whether they are the kind of company that takes it) formally opens the Greywell arc for a future module and marks the party, in the campaign\u2019s quiet ledger, as the people who came for the girls\u2019 sake. Declining is also a choice, and the jar of plums stays on the shelf either way, where everyone can see it."));

c5.push(H1("Diverging Paths (DM Only)"));
c5.push(P("Record outcomes in the Branch Ledger."));
c5.push(BUL("The report to Kessin:", "Truth (naming Shen) makes the party Kessin\u2019s proven instrument \u2014 better Highcourt access, future commissions, and Shen\u2019s cold, patient enmity: the alliance dies unborn and the Nyreeza trail must be walked without the spymaster\u2019s half of the evidence. Shen\u2019s cover story keeps the alliance and plants a lie in the Chamberlain\u2019s ledger that he may one day trace \u2014 if he does, the party\u2019s Highcourt credit burns at the worst possible moment. Refusing to report at all returns the fee and marks them, in Kessin\u2019s book, as honest and useless \u2014 the safest and least rewarded branch."));
c5.push(BUL("The Odell interview:", "Clean answers (no attribution to Vaelindra, no registration) deny the Office its bricks: the Session Six writ proceeds on weaker grounds and the legal counter-play there gains advantage. Any attribution statement strengthens the writ. Voluntary registration as claimants gives the Office lawful examination authority over the party themselves \u2014 a leash that will be pulled. Open defiance or insult accelerates everything and adds the party to the writ by name."));
c5.push(BUL("Mosse \u2014 cultivated vs. burned:", "Cultivated (commerce or the blotter ceremony), he becomes the campaign\u2019s standing window into the document underworld and a source of future leads. Burned (intimidation, exposure), Rivergate\u2019s paper trade closes to the party, and a future session\u2019s forged-document need becomes materially harder."));
c5.push(BUL("The Inkhands:", "An arrangement makes the docks friendly: eyes, small favors, and a warning the night something worse comes upriver. Blood makes the docks a place the party gets watched from doorways, forever."));
c5.push(BUL("The Farrowgate client (optional):", "Taken, the Greywell arc opens with the party as protagonists of conscience. Declined, the arc still exists \u2014 but it will eventually arrive as news of what happened while nobody came, which is a different kind of scene."));

c5.push(H1("Stat Blocks"));
SB({ name: "Inkhand Enforcer", meta: "Medium humanoid (any race), neutral",
  ac: "11 (leather armor)", hp: "32 (5d8 + 10)", speed: "30 ft.",
  str: 15, dex: 11, con: 14, int: 10, wis: 10, cha: 11,
  skills: "Athletics +4, Intimidation +2",
  senses: "passive Perception 10", langs: "Common, dockside cant", cr: "1 (200 XP)",
  traits: [{ n: "Pack Tactics", t: "The enforcer has advantage on attack rolls against a creature if at least one ally is within 5 feet of the creature and the ally isn\u2019t incapacitated." },
           { n: "Professional Standards", t: "The enforcer fights nonlethally by default (saps, fists, boat-hooks reversed) and quits at half hit points or when Halloc calls it. Killing is bad for the ledgers." }],
  actions: [
    { n: "Multiattack", t: "The enforcer makes two sap attacks." },
    { n: "Sap", t: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage (nonlethal by default)." }
  ] }).forEach(x => c5.push(x));
SB({ name: "Brune Halloc", meta: "Medium humanoid (human), neutral",
  ac: "13 (thick coat, quick head)", hp: "45 (7d8 + 14)", speed: "30 ft.",
  str: 17, dex: 12, con: 14, int: 12, wis: 13, cha: 14,
  skills: "Athletics +5, Insight +3, Intimidation +4, Persuasion +4",
  senses: "passive Perception 11", langs: "Common, dockside cant, river-sign", cr: "2 (450 XP)",
  traits: [{ n: "The Reasonable Option", t: "Halloc offers terms before, during, and after violence. Any turn in which a hostile creature speaks to him instead of attacking, he will pause his crew to hear it out." }],
  actions: [
    { n: "Multiattack", t: "Halloc makes two boat-hook attacks." },
    { n: "Boat-Hook", t: "Melee Weapon Attack: +5 to hit, reach 10 ft., one target. Hit: 7 (1d8 + 3) bludgeoning damage, and Halloc can pull a Medium or smaller target 5 feet toward him (his negotiating distance)." }
  ],
  reactions: [
    { n: "Hold Fast", t: "When an ally within 10 feet is reduced to half its hit points, Halloc calls the fight: his crew disengages and negotiations reopen at once." }
  ] }).forEach(x => c5.push(x));
SB({ name: "Office Examiner", meta: "Medium humanoid (any race), lawful neutral",
  ac: "14 (breastplate under gray robes)", hp: "22 (4d8 + 4)", speed: "30 ft.",
  str: 12, dex: 12, con: 12, int: 13, wis: 14, cha: 12,
  skills: "Insight +4, Investigation +3, Religion +3",
  senses: "passive Perception 12", langs: "Common, Old Imperial", cr: "1/2 (100 XP)",
  traits: [{ n: "Instruments of Examination", t: "The examiner carries a mancatcher, weighted cords, and sealed scrolls of restraint. Its purpose is custody, never death; it always attacks nonlethally and always announces its writ first." }],
  actions: [
    { n: "Mancatcher", t: "Melee Weapon Attack: +3 to hit, reach 10 ft., one Medium or Small creature. Hit: 4 (1d6 + 1) bludgeoning damage, and the target is grappled (escape DC 12). The examiner can\u2019t use the mancatcher on another target while it grapples." },
    { n: "Scroll of Binding (1/day)", t: "The examiner reads a sealed scroll: one creature it can see within 30 feet must succeed on a DC 13 Wisdom saving throw or be restrained by cords of gray light for 1 minute (save at end of each turn). The scroll is consumed." }
  ] }).forEach(x => c5.push(x));

c5.push(H1("NPC Profiles"));
c5.push(H3("Clerk Ossian Pell"));
c5.push(P("Human, mid-20s, the Chamberlain\u2019s office in miniature: gray, precise, forgettable by training. Speech: memorized phrasing, visible relief when questions stay inside the phrasing. Thread: Pell is the party\u2019s barometer for Kessin\u2019s regard \u2014 as their Highcourt standing rises or falls, Pell\u2019s manner (and the quality of the commissions he carries) shifts first."));
c5.push(H3("Tirell Mosse"));
c5.push(P("Human, 50s, dealer in defunct authorities and mourner of dead institutions. Speech: elegies for abolished offices; italicized discretion (\u201COne does not learn who; it is the entire point of me\u201D). Thread: cultivated, he is the document underworld\u2019s friendliest door and will someday sell the party something that matters enormously; burned, that door \u2014 and everything behind it \u2014 closes."));
c5.push(H3("Prelate Sarvin Odell"));
c5.push(P("Human, 60s, head of the Office of Omens; the antagonist of this arc and never once rude about it. Speech: soft, exact, kind in the way of surgeons; asks questions he has already answered in the file. He believes, sincerely, that unlicensed prophecy kills people \u2014 he has case files where it did \u2014 and that Vaelindra is a fifty-year failure of Church discipline he intends to correct before he retires. Thread: Odell is beatable by law, by politics, or by making his case collapse \u2014 but never by argument, and making it personal makes it worse. His file on the party survives every branch."));
c5.push(H3("Brune Halloc"));
c5.push(P("Human, 40s, Inkhand crew boss; violence as a customer-service failure. Speech: dockside proverbs, terms offered mid-swing. Thread: an arrangement with Halloc quietly makes the party \u201Cknown on the docks,\u201D which in Rivergate is a currency."));
c5.push(H3("Mistress Averil Shen"));
c5.push(P("Human, 50, Keeper of the Bureau of Correspondence; the stillest person in any room. Speech: economical, dry, honest exactly when honesty is the sharper instrument. Her loyalty question is the campaign\u2019s live wire: she was Nyreeza\u2019s creature, serves Qilvayas faithfully, and is withholding from him the one investigation he would most want \u2014 because his mother did. Thread: the alliance, if formed, gives the party the empire\u2019s best intelligence and its most dangerous friend; every secret they share with Shen is also a secret Shen has."));
c5.push(H3("The Widow Brakka"));
c5.push(P("Landlady, nationality unestablished and fiercely maintained as such, feeds everyone, fears nothing, negotiated with a mimic and won. Speech: rent dates and endearments in the same sentence. Thread: none. She is texture, and she is load-bearing texture; protect her at all costs."));

c5.push(H1("Loot and Found Rewards \u2014 Session Five \u2014 Dead Letters"));
c5.push(ltable(["Find","Value / Effect"],[40,60],[
  ["Commission & incidentals","Canon (150 gp; up to 100 gp Rivergate earnings)"],
  ["Mosse\u2019s goodwill (if cultivated)","A standing 10% at Defunct & Antiquarian, and first refusal on \u2018items of academic interest\u2019 \u2014 a loot table that walks in the door every few sessions"],
  ["Inkhand arrangement","Dock intelligence; one free \u2018misplaced cargo\u2019 favor"]
]));
c5.push(H1("Rewards and Advancement"));
c5.push(P("Coin: 150 gp commission (paid on any report), up to 100 gp in incidental Rivergate earnings, and Brakka\u2019s cooking. Relationships are the true treasure: Mosse, Halloc, Pell, and above all the Shen alliance \u2014 or its absence \u2014 define the campaign\u2019s intelligence landscape from here forward. Items: Shen\u2019s ciphered document (Nyreeza\u2019s final filing \u2014 unreadable until combined with the rubbing and Vell, Session Six), and optionally a jar of preserved plums with a weight out of all proportion to its size. XP for tables using it: roughly 900\u20131,300 depending on route (full value for every avoided fight). Milestone: the party remains 5th level; 6th comes at the Second Seal."));
c5.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 400, after: 200 }, children: [new TextRun({ text: "~", size: 24 })] }));
c5.push(new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "\u201CShe was cleverer than all of us. And on the last day anyone saw her, she filed one final document \u2014 and I cannot read it.\u201D", italics: true })] }));

// ============================================================
// SESSION 6 \u2014 THE SECOND SEAL
// ============================================================
const c6 = [];
title(c6, "Session Six: The Second Seal", "An adventure for 4\u20136 characters of 5th level \u2014 the dead letters read, the Church\u2019s hand forced, and the first descent");

c6.push(H1("Overview"));
c6.push(P("Everything converges. The Empress\u2019s two ciphered documents \u2014 the party\u2019s rubbing and Shen\u2019s final filing \u2014 go under Archivist Vell\u2019s eye and give up a translation that changes the shape of the campaign. The Office of Omens, its patience spent, executes its Writ of Examination against Vaelindra at the blue-shuttered house, and the party\u2019s choices decide her fate and their standing with the Church for years of play. Her hand forced, Vaelindra finally gives the party the middle tier of the truth she has carried for fifty years. And then, following a dead woman\u2019s bearings, the party opens a mason\u2019s door in the base of Zhuvedus\u2019s own monument and descends beneath the Old Forum \u2014 through the catacombs, past the First Seal, through the unquiet dead \u2014 to end the session standing before the Second Seal, in cold that has waited two thousand years to be felt again, listening to a sound they know from a dream."));
c6.push(P("Designed for a five-hour core. Pacing budget: reading the dead letters, and the hole in the Fourth Book (55 minutes); Shen, and what the translation is worth (25 minutes); the Writ at Ninth Lane, run in its four phases (75 minutes); Vaelindra\u2019s hand, forced (40 minutes); the descent through the seven keyed areas (70 minutes); the Second Seal (15 minutes, unhurried \u2014 it is the cliffhanger and the arc\u2019s final image). Optional content adds up to two further hours. The party reaches 6th level when the session ends at the Seal."));
c6.push(B("On the descent.", "Seventy minutes for seven areas is five minutes less than the previous budget allowed for the same journey, and it buys a great deal more, because the areas give the DM somewhere to put the time rather than a single long corridor to narrate. D2 and D4 are the two that must not be hurried; D1, D6, and D7 are each a single image. If the table is behind, D2\u2019s four hundred years of the capital\u2019s dead can be one paragraph instead of five minutes, and nothing structural is lost."));

c6.push(H2("What Is Actually Happening (DM Only)"));
c6.push(P("Nyreeza\u2019s two documents, combined, contain: a surveyed route into the Old Forum catacombs beginning at a mason\u2019s access door in the monument plinth; wardline notations for what she called the First Seal (an imperial-era barrier she breached, neatly, alone, three years ago); a depth, a bearing, and the phrase already known from the Cold Door \u2014 \u201Ccolder past the second seal\u201D \u2014 and a final passage in her personal cipher that Vell will read aloud once and never agree to repeat: \u201CIf I do not return: the wound predates the Wall. The Tablets were written over it. He must not follow me. Tell him the garden, not the grave.\u201D The first sentence confirms the campaign\u2019s buried truth from the Empress\u2019s own hand. The second \u2014 that the Golden Tablets, the empire\u2019s sacred founding law, were composed over the wound \u2014 is a revelation whose full meaning should be allowed to detonate slowly across many sessions. The third is a mother\u2019s protection order. The fourth is a private code between Nyreeza and her son that no one at the table can yet unlock \u2014 it keys to the sealed dispatch case in the Empress\u2019s study, and it is the campaign\u2019s promise that this thread runs through the throne itself."));
c6.push(P("Meanwhile, Odell moves. His writ \u2014 stronger or weaker depending on the Session Five interview \u2014 authorizes the Examination of Vaelindra of the Still Waters on grounds of unsanctioned interpretation of divine contact. Examination is not execution: it is custody, questioning, and \u201Cresolution into a file,\u201D which for a woman of her age and knowledge might mean comfortable house arrest in a Sanctum cell for the rest of her life, every ledger she owns confiscated and read. Odell believes he is protecting people. The writ is legal. That is the problem the party must actually solve \u2014 the law is not on the side of the truth, which is this campaign\u2019s oldest joke and the least funny one."));

c6.push(H1("Scene 1: Reading the Dead Letters"));
c6.push(BOX("The Overdue Volume is a teahouse two lanes off Scholar\u2019s Row where the academy\u2019s retired and disgraced drink leaf-water strong enough to trot a horse, and where the proprietor enforces silence with a look that has ended marriages. Vell holds a corner table the way a fortress holds a pass. He examines both documents for eleven minutes by the clock without speaking, and the party gets to watch a man read his own past: he archived nine years of this hand. When he finally speaks, it is to the tabletop. \u201CI will read it once. I will not repeat it. And then, colleagues, you are going to tell me everything, and for the first time in forty years I am going to leave my ledgers unbalanced and help you.\u201D"));
c6.push(P("Give the translation scene its full hour: the mechanics of the cipher (Vell narrating Nyreeza\u2019s shorthand habits with terrible tenderness \u2014 she crossed her sevens; she abbreviated \u2018forever\u2019; her hand shakes only in the final passage), the route, the seals, and the last four sentences landing one at a time. Let the players sit with \u201CThe Tablets were written over it\u201D without any NPC explaining it. Vell\u2019s contribution beyond translation: he can confirm from archive records that the monument plinth\u2019s mason-door exists (a maintenance access, sealed by custom, not lock \u2014 masons\u2019 guild superstition holds that work on the Founder\u2019s monument is \u201Cpaid in bad years\u201D), and he identifies the final line as private code with the certainty of a man who sorted the Empress\u2019s personal correspondence: \u201CThat sentence has an addressee, and the addressee wears a crown. What you do with that fact will define you. Choose slowly.\u201D"));

c6.push(H1("Scene 2: What the Translation Is Worth"));
c6.push(P("If the Shen alliance stands, she must be told something \u2014 the documents were pooled on terms. Thirty minutes of genuine strategic table-talk: does the party share the full translation (Shen, hearing \u201CHe must not follow me,\u201D goes silent for a long moment and then says, very quietly, \u201CThen she was protecting him. Three years I wondered. Thank you\u201D \u2014 and the question of whether Shen now tells the Emperor becomes hers, and live), a partial version (she knows within days that it is partial; the alliance survives exactly one such discount), or nothing yet (breach of terms; she does not threaten, she simply notes it, which is worse). If there is no alliance, this scene becomes the party alone with the knowledge, and the DM should let the silence of that \u2014 nobody in the world knows what they know \u2014 do its work. Either way, the scene ends with the same interruption: a breathless runner from Coppergate. Gray robes at Ninth Lane. Many of them."));

c6.push(H1("Scene 3: The Writ at Ninth Lane"));
c6.push(BOX("They have blocked both ends of the lane with the quiet efficiency of people who practice: eight examiners in Office gray, a censor-captain in half-armor beneath his robes, and Prelate Odell himself, standing before the blue shutters with a document in both hands like a man presenting a gift. The copyist\u2019s shop below is shuttered \u2014 its proprietor nowhere in sight, which tells its own story. A small crowd of Coppergate neighbors has gathered at the barriers, and they are not neutral: this is their district, and the old woman upstairs has read the weather and the omens for their grandmothers. Above, one blue shutter stands open. She is watching. She does not look surprised. She looks like a woman confirming a fifty-year-old appointment."));
c6.push(P("This is the session\u2019s crucible, seventy-five minutes, and it must be run so that every path is real. The writ is legal; force is the worst answer available; and the scene is built so that the party\u2019s accumulated choices \u2014 the Odell interview, the Highcourt standing, the Shen alliance, their Seal-house training \u2014 are the arsenal. Four principal resolutions, any of which can succeed or fail forward:"));
c6.push(BUL("A \u2014 The Law:", "The writ\u2019s ground is \u201Cunsanctioned interpretation of divine contact.\u201D A Seal-trained challenge, argued on the spot or before a magistrate within the hour: Vaelindra has interpreted nothing \u2014 she takes testimony and cites historical pattern; she claims no contact and counsels no claimants (if the party avoided registering in Session Five, this is where that pays: DC 15 Charisma (Persuasion) with advantage; a registered party argues at disadvantage and Odell smiles through every word). Success does not kill the writ \u2014 it suspends it pending review, buying months and humiliating the Office publicly, in front of the district. Odell accepts defeat like a professional and begins building the next writ that afternoon."));
c6.push(BUL("B \u2014 The Politics:", "A Highcourt marker \u2014 Kessin\u2019s favor (if earned and kept), or Shen\u2019s intervention (the Bureau can \u201Cdiscover\u201D that the Examination of a witness in an open imperial inquiry is obstruction) \u2014 quashes the writ from above. Cost: the marker is spent, the benefactor now owns a piece of Vaelindra\u2019s freedom, and the Church logs precisely who reached over its head. Corvane herself takes note of the party\u2019s name for the first time \u2014 which cuts both ways forever."));
c6.push(BUL("C \u2014 The Vanishing:", "Extraction \u2014 the party\u2019s own plan over the rooftops, or Shen\u2019s people, or the Coppergate crowd \u201Caccidentally\u201D breaking the cordon. Vaelindra escapes into a life in hiding (Shen\u2019s safehouse, the party\u2019s office, or \u2014 the branch with teeth \u2014 an offer of sanctuary that arrives, within days, from the See of Orlath, which delights in sheltering the capital Church\u2019s victims). She is safe, and the party has made her a fugitive and themselves accessories; the Office\u2019s next writ names them."));
c6.push(BUL("D \u2014 The Surrender:", "Vaelindra\u2019s own preference, if the party has no better card and asks her honestly: she goes with them, upright, in front of her district \u2014 and the party works her release from outside (any of A or B pursued afterward, harder). She has survived the Church for fifty years; she can survive its hospitality for a season. \u201CBut come for me,\u201D she says, at the door, without drama, \u201Cbecause the ledgers go with me, and I have not finished teaching you to read.\u201D"));
c6.push(P("Violence deserves its own warning label rather than a lettered branch: the examiners fight nonlethally and the party can absolutely win the lane \u2014 and lose the campaign\u2019s civic ground. Assaulting a lawful Church examination in public makes the party fugitives of the Sanctum, locks the capital\u2019s institutions against them for an act, and hands Odell the only thing his case lacked: proof that Vaelindra\u2019s circle is dangerous. If the table goes this way, let it \u2014 consequences are content \u2014 but make the cost legible before the first sword clears leather: Vaelindra herself, from the window, calling down \u201CChildren. Not like this. I have not spent fifty years being careful so that you could spend me in an afternoon.\u201D"));

c6.push(H1("Scene 4: Her Hand, Forced"));
c6.push(P("Whichever branch resolved the lane, this scene follows within a day \u2014 in her apartment, a safehouse, or the visiting room of a Sanctum cell (Odell permits visitors; recorded, naturally; she and the party may enjoy speaking entirely in weather metaphors). Vaelindra has decided: the Office\u2019s move ended the luxury of her silence, and the party has earned \u2014 or events have forced \u2014 the middle tier of fifty years of knowledge. She gives them, in her physician\u2019s cadence, with the ledger (or its memory) open before her:"));
c6.push(BUL("The vision that ended her career,", "fifty years ago, entire for the first time: not the burning city \u2014 that came to others \u2014 but the founding itself, seen from below: \u201CI saw that the founding was a burial. I saw the first Emperor stand over something that had trusted him, in a place that became the Old Forum, and I saw the law itself laid down upon it like a stone upon a grave. I reported it faithfully. Within a month I was a file. That is how I know your Prelate\u2019s office is very good at its work: I was trained in its methods, and I trained others.\u201D"));
c6.push(BUL("What Nyreeza sought,", "and what she and Vaelindra said at that last meeting: the Empress had found the same shape from the other direction \u2014 records, requisitions, dead seals \u2014 and came not for interpretation but for confirmation. \u201CShe asked me one question: \u2018Is it still there?\u2019 And I told her the truth, which is that it was never anywhere else. She thanked me. She was the only person in fifty years who believed me the first time. And then she went down alone, because she was an Empress and the mother of an Emperor, and she would not risk anyone she ruled. Her hand shakes in that cipher because she already knew she was not coming back up.\u201D"));
c6.push(BULLET([{ t: "The warning, and the withholding: ", b: true }, { t: "\u201CWhat is under the Forum is a wound, and wounds this old have names, and I will not say them \u2014 not from mystery, but because names have weight down there, and you have not yet earned the strength to carry them. Go and stand where she stood. Read what she read. Come back alive, and I will give you the names, and you will wish I hadn\u2019t. And children \u2014 the Emperor. His mother\u2019s last sentence was for him, and it was \u2018do not follow.\u2019 Honor it a while longer. The day you bring the throne into this, you cannot bring it back out.\u201D (" }, DM("DM note: "), { t: "she is deliberately withholding Threnvos, Zhuvedus\u2019s fall, and the oath-mechanism \u2014 the full account remains the mid-campaign payoff, canon-per-sourcebook, once the party returns from the threshold.)" }]));

c6.push(H1("Scene 5: The Descent"));
c6.push(BOX("At night the Old Forum belongs to the mad, the destitute, and the stone. Zhuvedus\u2019s monument stands at its heart the way it has for twenty centuries \u2014 a robed figure, features worn to suggestion by two thousand years of hands touching the hem for luck \u2014 and at the base of the plinth, exactly where a dead woman\u2019s bearings say, a mason\u2019s access panel opens on hinges that someone oiled three years ago. The stair beneath is pre-imperial: black stone, fitted without mortar, treads worn hollow in the middle by feet that predate the empire whose founder stands above. The cold begins on the ninth step. The medallion begins on the tenth."));
c6.push(P("Run the descent in three movements across seventy-five minutes:"));
c6.push(BUL("The Bone Galleries:", "Imperial-era catacombs \u2014 centuries of Aenodira\u2019s dead in wall niches, oldest at the bottom, and Nyreeza\u2019s survey cipher blazing the route at every fork like a trail of quiet fireflies (finding each mark: DC 12 Investigation, automatic for the rubbing\u2019s carrier). Skill texture, not combat: a collapsed gallery to bypass (Athletics/engineering), a flooded stretch (the Ostrun leaks), and the growing wrongness \u2014 every niche within thirty feet of the true route holds dead that lie perfectly, unnaturally undisturbed, as though nothing that scavenges will come near."));
c6.push(BUL("The First Seal:", "A full imperial wardline across the passage \u2014 wolf-standard sigils, Old Imperial invocations, professional work of the founding era \u2014 with a neat, surgical breach at its base: Nyreeza\u2019s work, three years old, annotated in her cipher with the date and a single word: \u201Calone.\u201D The wards are dead where she cut them and dying elsewhere; a detect-magic reading shows the whole line fading like an old scar, which raises the question no one need answer aloud: the First Seal was maintained, once. By whom, and when did they stop? Passing the breach, every character feels the temperature drop as a pressure rather than a chill; the medallion\u2019s carrier makes a DC 12 Constitution save or takes a level of exhaustion\u2019s cold cousin \u2014 no mechanical penalty, just the DM\u2019s note that their breath now fogs when no one else\u2019s does."));
c6.push(BUL("The Unquiet:", "Past the First Seal, the interment niches are older than the empire \u2014 and the nearest dead do not rest. The Hollow Dead rise: 4 (5 for five characters, 6 for six) plus the Sepulcher Chill, a colder and older thing wearing the gallery\u2019s dark like a garment. They do not moan; they whisper \u2014 and a character who listens (or fails a save) catches the words, which are the vision\u2019s imagery in the mouths of the pre-imperial dead: the storm, the wrong fire, the shape behind the sky. They have been dreaming it down here longer than the empire has existed. Radiant damage and daylight-grade light are the tactical keys; the Chill dissolves rather than dies, flowing not away from the party but deeper \u2014 toward where they are already going."));
c6.push(H2("Scaling the Unquiet"));
c6.push(P("Baseline (4 characters, 5th level): 4 Hollow Dead + the Sepulcher Chill in a two-wave rhythm (dead first, Chill from the dark on round 2) \u2014 an adjusted-hard encounter with the environment as the real enemy (niched terrain, 10-foot visibility past torchlight). Five characters: +1 Hollow Dead. Six: +2, and the Chill opens the fight already manifested. The party should end this fight resourced-down and rattled; the session\u2019s final scene is meant to be walked into tired."));

c6.push(H1("Scene 6: The Second Seal"));
c6.push(BOX("The gallery ends, and the architecture changes \u2014 not built, but hewn: a single vault of the black mortarless stone, older than every bone behind you, and at its far side, the door. You know it before the light reaches it, because your body knows it: the Cold Door beneath the academy was a postern \u2014 this is the gate. Twenty feet of black stone furred white with frost in air that has never known winter, worked across its whole face with carvings your academy educations have no alphabet for \u2014 and, small and human at its foot, the last of Nyreeza\u2019s marks: her cipher, and beside it, scratched deeper and less steadily, in plain Imperial anyone can read \u2014 the word she wrote when the cipher stopped being enough: FORGIVE. The medallion is a coal of cold against its carrier\u2019s chest. And through twenty feet of stone that has held for two thousand years, faint and vast and patient, comes a sound. You know it. You have known it since a night at the Gilded Ford. On the far side of the Second Seal, something that has always been here is breathing in its sleep \u2014 and as you stand there, in the deepest cold of the oldest dark, it turns over."));
c6.push(P("End the session there \u2014 on the sound, the word, and the cold. Do not open the Seal; do not let anything come through; do not resolve. If a player attempts to force or magic the door, let every attempt fail with total, geological indifference and one consequence: the sound pauses. Listening. Then resumes. That is enough. Milestone: the party reaches 6th level on the walk back up into the lamplight of a city that has no idea what it is standing on. The next arc \u2014 what the Seal requires, what Vaelindra\u2019s names cost, and what happened to the woman who wrote FORGIVE \u2014 begins with Session Seven."));


// ============ SESSION SIX ADDITIONS ============
c6.push(H1("The Descent, Keyed"));
c6.push(P("Scene 5 takes the party under the Old Forum for the first time, and the route matters, because they will use it again in Sessions Seven and Eight and because a route the players have mapped is a route they own. Seven areas from the Forum floor to the Second Seal."));
c6.push(B("The shape of it.", "Down, and then east. The public stair on the Forum\u2019s east side serves the upper Bone Galleries and stops at a consolidation hoarding that has been there since before living memory. Behind the hoarding the galleries continue down four more levels, and at the bottom of the fourth the masonry changes and the Undercourt begins. The funerary traffic never comes below the second level, which is why this route is available and why nobody has walked it in a century."));
c6.push(B("D1. The East Stair.", "Public, lit, swept, and entirely ordinary. Vigil-keepers pass here at all hours and will nod. This is the last well-lit place for two sessions."));
c6.push(B("D2. The Upper Galleries.", "Two levels of interments, oldest at the bottom, arranged in wall-niches by century. Dry, cold, and profoundly peaceful. Nothing here is hostile. A party that hurries through misses the point: this is where every Zhuvedian in the capital ends up, and the party is about to walk past four hundred years of them."));
c6.push(B("D3. The Consolidation Hoarding.", "Timber, painted, official, and eighty years old. A notice board beside it carries a work order that was never completed. The hoarding is not locked. It is simply a hoarding, and going past it is a decision rather than a break-in \u2014 which is exactly the kind of threshold this campaign likes."));
c6.push(B("D4. The Closed Galleries.", "Two more levels, unswept, undisturbed, and \u2014 the first genuinely wrong thing \u2014 noticeably colder than the levels above, in a place where depth should mean warmth. A DC 13 Wisdom (Survival) or any character who has held Dren\u2019s medallion knows that is backwards."));
c6.push(B("D5. The Change of Stone.", "Imperial brick gives way to black stone fitted without mortar, the same as the Cold Door and the same as the Founder\u2019s Wall a mile above. There is no doorway; the two masonries simply meet, and one of them was there first."));
c6.push(B("D6. The Approach.", "A corridor that is not a corridor: too wide, too tall, and proportioned for a procession. The Undercourt proper. Sound behaves oddly here and the party will notice before the DM says anything."));
c6.push(B("D7. The Second Seal.", "Where the session ends. See the scene text; nothing in this keying replaces it."));

c6.push(H1("The Writ at Ninth Lane (Set Piece, in Phases)"));
c6.push(P("Scene 3 is the session\u2019s set piece and it is a siege of paperwork, not of walls. Run it in four phases with a decision at each transition. The Office of Omens does not break down doors; it arrives with a document, and the horror of the scene is that everything Censor-Captain Odo does is lawful."));
c6.push(B("Phase One \u2014 The Knock (10 minutes).", "Odo arrives with four and knocks. He presents a Writ of Examination naming Vaelindra, and he waits to be admitted. The decision: does the party open the door? He will wait a long time. He has waited before. Refusing is legal, costs nothing immediately, and changes the whole scene into a siege \u2014 which is what he would prefer, because a siege is a fact he can write down."));
c6.push(B("Phase Two \u2014 The Reading (15 minutes).", "Admitted or not, the Writ is read aloud in full, at the door or through it. It is long, it is precise, and it is correct. The decision: does anyone challenge it on its own terms? A DC 15 Intelligence (History) or any character with a legal background finds the defect \u2014 the Writ names Vaelindra and does not name her premises, which under Book Four means it authorizes examination of a person and not a search of a house. Odo will concede the point instantly and courteously, because he is not a liar, and will then simply ask her to come with him, which is what the Writ actually permits."));
c6.push(B("Phase Three \u2014 The Choice (20 minutes).", "Vaelindra\u2019s hand is forced. The decision belongs to her and the party can influence it, and the module must let them fail: she can go, which ends the immediate danger and begins a much worse one; or she can refuse, which makes her a fugitive within the hour. What the party says here matters more than any check. Ask for a stated argument, not a roll."));
c6.push(B("Phase Four \u2014 The Departure (20 minutes).", "Whatever was chosen, Odo leaves, and how he leaves is the phase. If violence has occurred, he is a wounded officer with witnesses and the party are now a filed matter. If it has not, he leaves a copy of the Writ, thanks them, and \u2014 this is the line to deliver carefully \u2014 asks each of them their name, and writes them down, and does not react to any of them."));
c6.push(PS([DM("DM Only: "), { t: "Odo believes he is protecting the empire from a hundred unlicensed prophets and he is, in the main, correct. Play him warm. He should be the most reasonable person in the room and the party should not be able to hate him cleanly, because the campaign\u2019s whole argument is that institutions do terrible things through people who are behaving well. If the table wants a villain here, refuse to supply one." }]));

c6.push(H1("The Fourth Book Concordance (Puzzle)"));
c6.push(P("Scene 1 is the party reading what they recovered, and as written it is a translation. Make it a reconstruction: the letters give a set of register citations, and the citations point at a hole. The puzzle is noticing the shape of an absence."));
c6.push(BOX("Six citations, all to the Fourth Book, of Seals and Record. Five of them resolve: ordinary deposit entries, dry as chalk, dated across one season twelve years ago. The sixth resolves to an entry that says a document was DEPOSITED and does not say by whom, in a register whose whole purpose is to say by whom. And when you check the five that worked, all five have the same Hand, and it is not the Hand of the clerk who was working that season."));
c6.push(B("What it means.", "Somebody deposited six items under a borrowed clerk\u2019s hand and left one of them unattributed. That is not a forgery; it is worse and quieter. It is somebody with legitimate access using it in a way the register cannot describe."));
c6.push(B("Solution one \u2014 the concordance.", "With Mosse\u2019s secondhand concordance, DC 13 Intelligence (Investigation) resolves all six citations in an hour. The sixth is the finding and it announces itself."));
c6.push(B("Solution two \u2014 Vell.", "Take it to the Archivist. He will resolve it in four minutes, go very quiet, and then be extremely careful about what he says next \u2014 because the Hand in question is one he knows, and it has no business being on those entries, and he has spent twelve years not asking himself why."));
c6.push(B("Solution three \u2014 the register itself.", "Go to the Archive and pull Book Four for that season. Slow, public, and it works, and it also means the party\u2019s names are now on a request slip in the archive\u2019s own record, which is a real cost and should be stated after they do it, not before."));
c6.push(B("Solution four \u2014 the negative.", "A party who never resolves the citations at all can still get there by asking who was clerking that season and finding that the answer is one person who was demonstrably somewhere else. This is the hardest route and the most satisfying, and a DM should be ready for it because clever tables find it."));

c6.push(H1("Traps and Hazards on the Descent"));
c6.push(B("The Hoarding (D3).", "No mechanics. Stated here because a DM will want to put a lock on it and should not. The whole point is that nothing prevents them. Going past a notice that says do not is the session\u2019s real threshold and it should cost nothing but nerve."));
c6.push(B("The Cold (D4 onward).", "Environmental. Marked thin-written ground, worsening with depth. Long rests taken below D4 restore half the usual Hit Dice. Ritual casting takes twice as long and may simply fail. Divination returns grief rather than answers \u2014 and a DM should have one specific, personal, useless piece of grief ready for each player character, because that is far more frightening than a failed spell."));
c6.push(B("The Niche Fall (D2 and D4).", "Mechanical hazard. Eight hundred years of interments in wall-niches, and the mortar in the closed galleries has gone. A creature that climbs, braces against, or fights beside a niche wall: DC 12 Dexterity save or a section gives \u2014 2d6 bludgeoning, and the party is now standing in somebody. There is no monster in this. The horror is entirely in the apology."));

c6.push(H1("Encounters in the Galleries"));
c6.push(P("Roll a d8 on the descent, once per level below the hoarding. Most of these are not fights, and that is the level\u2019s whole atmosphere."));
c6.push(ltable(["d8", "What Happens"], [11, 89], [
  ["1", "A vigil-keeper on the upper galleries, working late, who will talk about the consolidation hoarding and what she has heard behind it."],
  ["2", "A niche with a lamp burning in it. Fresh oil. Four levels below where anyone goes."],
  ["3", "Rats, and then the absence of rats, which is worse and which happens one level lower."],
  ["4", "A Thin-Written Echo (see the Gazetteer\u2019s bestiary) repeating one gesture from a funeral eight hundred years ago."],
  ["5", "A collapsed section of gallery revealing a level below that is on no plan the Church holds."],
  ["6", "Cold that arrives as a front, moving, and passes over the party in about four seconds, and does not come back."],
  ["7", "A Vigil-Wight (see the Gazetteer\u2019s bestiary) in the closed galleries, unwatched for a century. It can be laid to rest by keeping its Vigil, and the party has somewhere else to be, and that is the encounter."],
  ["8", "Their own light, reflected off something a long way ahead that should not be reflective."]
]));

c6.push(H1("Handout \u2014 Session Six"));
c6.push(H2("The Writ of Examination"));
c6.push(BOX("BY THE OFFICE OF OMENS, under the Third Book, of the Sanction and the Charter, and by the writ of the Synod of the Grey: TO VAELINDRA, called of the Still Waters, of the parish of the Ninth Lane, greeting. You are required to present yourself for examination touching claims of divine contact received and interpreted without Sanction. This writ is served upon your person. You may bring one companion. You are not accused. \u2014 F. ODO, Censor-Captain, for the Prelate of the Office."));
c6.push(P("Note for the DM: read You are not accused in exactly the tone of a man who means it, because he does. And note what the writ does not say: it names her person and not her house, which is the defect in Phase Two, and it is right there on the paper for any player who reads the handout carefully instead of listening to it."));
c6.push(H1("Optional Content (Beyond the Five-Hour Core)"));
c6.push(B("The Tarnovar Envoy (~45 minutes):", "A rare Tarnovari trade delegation is in the capital \u2014 stone-touching, oath-shy, unsettling the Exchange \u2014 and their evening at the Patched Standard includes a performance by their singer, Ilinca Verath: the Lament of Vosthren the Betrayed, in Tarnovari, translated in murmurs by a homesick clerk at the next table. The party hears, without any mechanical prompt, a two-thousand-year-old ballad describe a sworn covenant, a beloved traitor, and a grief buried \u2018beneath the victor\u2019s house.\u2019 No one else in the room reacts. Design function: the campaign\u2019s deepest secret, performed openly in a tavern, audible only to the people who have stood at the door it describes. If a party member speaks with Ilinca afterward, she is warm, proud of the old songs, and entirely ignorant of their truth \u2014 which is its own kind of chilling. Seeds the Tarnovar arc; record interest in the Branch Ledger."));
c6.push(B("Race-Day (~40 minutes):", "A Golds-and-Greys race-day on the Long Course \u2014 the capital at its loudest and most alive: faction chants, terrible meat skewers, a photo-finish dispute adjudicated by a magistrate with a speaking-trumpet, and the party\u2019s first ground-level read of the civic machine that will someday produce the Grey-Gold Rising. Pure texture plus one planted observation for attentive players: both factions\u2019 chants are loyalty songs to the city \u2014 and neither mentions the Emperor at all."));
c6.push(B("The Plums Come Back (~30 minutes):", "If the party took the Farrowgate client in Session Five: a follow-up scene \u2014 the mother returns with the daughter\u2019s final unsent letter, recovered from a teamster, describing the Countess\u2019s \u2018night garden\u2019 and a rule about singing after dark. If they declined: the scene arrives anyway, colder \u2014 the mother does not come back, and Brakka reports she has taken passage south alone, to knock on Greywell\u2019s gate herself. If a party member healed her cough in Session Five, it is back \u2014 not as a rebuke, and not as a mystery: she went home to the same rooms and the same water. Either branch sharpens the future module and keeps the jar of plums on the shelf doing its quiet work."));

c6.push(H1("Diverging Paths (DM Only)"));
c6.push(P("Record outcomes in the Branch Ledger. Session Six is the arc\u2019s great branching point \u2014 handle its consequences with the weight they deserve."));
c6.push(BUL("The Writ (A/B/C/D/violence):", "A (law) \u2014 Vaelindra free, Office humiliated locally, Odell rebuilding; Church standing recoverable. B (politics) \u2014 free at the price of a spent marker and Corvane\u2019s attention; the benefactor holds a piece of her. C (vanishing) \u2014 free and fugitive; party implicated; the Orlath sanctuary offer opens a door to the See that no other branch opens this early. D (surrender) \u2014 she is in Sanctum custody, composed, recorded, and expecting rescue-by-law; her ledgers are in Office hands, which will matter. Violence \u2014 fugitive branch for the party; capital institutions lock; Odell vindicated. Every branch keeps Vaelindra alive and the campaign\u2019s spine intact; what changes is the cost of reaching her and who owns the favors."));
c6.push(BUL("The translation and Shen:", "Full disclosure deepens the alliance and hands Shen the \u2018He must not follow\u2019 question \u2014 her decision about the Emperor becomes a live NPC arc the DM controls. Partial disclosure survives once. Silence breaks the alliance quietly. No alliance at all: the party owns the truth alone, and the campaign\u2019s loneliness dial turns up a notch."));
c6.push(BUL("The throne (major gate):", "If the party defies both Nyreeza\u2019s last sentence and Vaelindra\u2019s counsel and brings any of this to Qilvayas or his court now, do not block it \u2014 but treat it as the campaign\u2019s single largest divergence: the early-throne branch collapses the slow-burn structure and must be improvised with care. Recommended handling: access friction (Kessin\u2019s desk, remember) buys the DM one session of delay to prepare; and \u2018the garden, not the grave\u2019 gives Qilvayas a reason to receive the message in private and act slowly. Flag this branch prominently in the Ledger if it opens."));
c6.push(BUL("The Seal, forced:", "Attempts to open the Second Seal now fail, full stop \u2014 but a party that persists loudly (sustained magical assault, demolition) earns a consequence: the Unquiet do not trouble them on the way out, because everything down there is listening to the door instead. Note it in the Ledger as \u2018the Seal has heard them.\u2019"));
c6.push(BUL("The envoy (optional):", "If any character engaged Ilinca or the delegation, Tarnovar\u2019s thread warms: the envoy will remember the southerners who honored the old songs, and the future Tarnovar arc opens with a friendly face instead of a cold border."));

c6.push(H1("Stat Blocks"));
SB({ name: "Hollow Dead", meta: "Medium undead, neutral evil",
  ac: "13 (hardened grave-wrappings)", hp: "39 (6d8 + 12)", speed: "30 ft.",
  str: 15, dex: 12, con: 15, int: 5, wis: 10, cha: 6,
  resist: "necrotic; bludgeoning, piercing, and slashing from nonmagical attacks",
  vuln: "radiant",
  condimmune: "charmed, exhaustion, frightened, poisoned",
  senses: "darkvision 60 ft., passive Perception 10", langs: "understands the whisper it repeats", cr: "1 (200 XP)",
  traits: [{ n: "The Whisper", t: "The Hollow Dead constantly murmurs fragments of the shared vision in a pre-imperial tongue. A creature that starts its turn within 10 feet and can hear must succeed on a DC 12 Wisdom saving throw or hear one intelligible phrase in its own language (the storm, the wrong-colored fire, the shape behind the sky) and have disadvantage on its next attack roll. A creature that has experienced the vision automatically understands every word, and knows it." },
           { n: "Sunlight Sensitivity", t: "In daylight-grade light, the Hollow Dead has disadvantage on attack rolls and Wisdom (Perception) checks that rely on sight." }],
  actions: [
    { n: "Grave-Cold Grasp", t: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) bludgeoning damage plus 3 (1d6) cold damage." }
  ] }).forEach(x => c6.push(x));
SB({ name: "Sepulcher Chill", meta: "Large undead (residue-touched), chaotic evil",
  ac: "13", hp: "68 (8d10 + 24)", speed: "0 ft., fly 40 ft. (hover)",
  str: 6, dex: 16, con: 16, int: 7, wis: 12, cha: 10,
  resist: "acid, cold, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks",
  immune: "necrotic, poison", vuln: "radiant",
  condimmune: "charmed, exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained",
  senses: "darkvision 120 ft., passive Perception 11", langs: "\u2014", cr: "3 (700 XP)",
  traits: [{ n: "Incorporeal Movement", t: "The Chill can move through other creatures and objects as if difficult terrain, taking 5 (1d10) force damage if it ends its turn inside an object." },
           { n: "Unnatural Cold", t: "A creature that starts its turn within 5 feet of the Chill takes 3 (1d6) cold damage. Nonmagical flames within 30 feet gutter to half light." },
           { n: "Dissolution Deeper", t: "Reduced below one-quarter of its hit points or struck twice by radiant damage, the Chill shrieks soundlessly and pours away through the floor seams \u2014 always, unmistakably, in the direction the party is heading." }],
  actions: [
    { n: "Multiattack", t: "The Chill makes two touch attacks." },
    { n: "Sepulcher Touch", t: "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) cold damage, and the target must succeed on a DC 13 Constitution saving throw or its speed is reduced by 10 feet until the end of its next turn as the cold takes the knees first." }
  ] }).forEach(x => c6.push(x));
SB({ name: "Censor-Captain Ferrin Odo", meta: "Medium humanoid (human), lawful neutral",
  ac: "16 (half plate under gray robes)", hp: "52 (8d8 + 16)", speed: "30 ft.",
  str: 14, dex: 11, con: 14, int: 12, wis: 15, cha: 13,
  saves: "Con +4, Wis +4", skills: "Athletics +4, Insight +4, Religion +3",
  senses: "passive Perception 12", langs: "Common, Old Imperial", cr: "3 (700 XP)",
  traits: [{ n: "Letter of the Writ", t: "Odo announces his legal authority at the start of any confrontation and repeats it once per round as a free action. He and examiners under his command fight nonlethally without exception; a creature reduced to 0 hit points by them is stable and in custody." },
           { n: "Discipline of the Office", t: "Examiners within 30 feet of Odo have advantage on saving throws against being frightened." }],
  actions: [
    { n: "Multiattack", t: "Odo makes two weighted-staff attacks." },
    { n: "Weighted Staff", t: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) bludgeoning damage (nonlethal), and the target must succeed on a DC 13 Strength saving throw or be knocked prone." },
    { n: "Invocation of Stillness (Recharge 5\u20136)", t: "Odo intones a Church binding. Each creature of his choice within 30 feet that can hear him must succeed on a DC 13 Wisdom saving throw or be unable to take reactions and suffer half speed until the end of its next turn." }
  ] }).forEach(x => c6.push(x));
c6.push(P("Office Examiners at the Writ: use the Office Examiner stat block from Session Five (eight present; they act on Odo\u2019s orders and stand down instantly on any lawful resolution)."));

c6.push(H1("NPC Notes"));
c6.push(B("Prelate Sarvin Odell:", "See Session Five. At the writ he is the same man at higher stakes: correct, unhurried, and privately braced to lose \u2014 he has read the party\u2019s file and rates them. If beaten by law or politics he extends professional respect; if beaten by violence he extends a warrant."));
c6.push(B("Censor-Captain Ferrin Odo:", "Career Church soldier; took this posting because custody work \u2018keeps men honest.\u2019 Follows lawful outcomes to the letter, including ones that thwart him. Thread: Odo is winnable \u2014 a party that resolves the lane without blood earns his quiet regard, and a Church soldier\u2019s quiet regard is a strange key that will open a strange door someday."));
c6.push(B("Ilinca Verath (optional):", "Tarnovari singer, keeper of the old lament cycle, joyous and homesick and completely unaware of what she carries. Thread: the future Tarnovar arc\u2019s friendly face, if befriended."));

c6.push(H1("Loot and Found Rewards \u2014 Session Six \u2014 the Second Seal"));
c6.push(ltable(["Find","Value / Effect"],[40,60],[
  ["Pre-imperial grave goods (the Bone Galleries)","Silver torcs and burial honors, 120 gp scrap value \u2014 and a live moral tripwire: Church law vests grave goods in the Matron; selling them is a crime, and (DM note) carrying them out of the catacombs makes the bearer\u2019s dreams cold for seven nights. The loot table is also a test. That is the setting"],
  ["First Seal ward-fragment","Wardstone Shard (homebrew, below)"],
  ["Nyreeza\u2019s survey chalk","Mundane. A half-used stick of surveyor\u2019s chalk, imperial issue, three years old. Heartbreaking. Free"]
]));
c6.push(H1("Rewards and Advancement"));
c6.push(P("Coin: little \u2014 this session pays in truth. Items and intangibles: the full translation of the Empress\u2019s last words; the mapped, marked route to the Second Seal (the campaign\u2019s new fixed landmark); Vaelindra\u2019s middle-tier account and her promise of the names; the Writ\u2019s outcome with all its owed and owing favors; and the word FORGIVE, which the party will carry longer than any treasure. XP for tables using it: roughly 1,700\u20132,300 across the descent and the lane (full value for lawful resolutions). Milestone: 6th level at session\u2019s end, at the Seal. The first thirty hours of The Qilvayas Symphony are complete."));
c6.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 400, after: 200 }, children: [new TextRun({ text: "~", size: 24 })] }));
c6.push(new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "FORGIVE", italics: true })] }));

// ---------- write both ----------
Promise.all([
  Packer.toBuffer(docShell(c5)).then(b => fs.writeFileSync(stagePath("QS_Session_5_Dead_Letters.docx"), b)),
  Packer.toBuffer(docShell(c6)).then(b => fs.writeFileSync(stagePath("QS_Session_6_The_Second_Seal.docx"), b))
]).then(() => console.log("Both written."));
